"""
Serve STEP Studio (the CAD viewer) under a sub-path of this dashboard.

The dashboard runs on a subdomain root and gates every request behind a login
cookie, so a static app published alongside it needs three things this module
provides:

  1. **A mount** at ``/stepstudio`` serving the built static files.
  2. **An auth exemption**, so the viewer is reachable, and so its own asset
     requests are not answered with the dashboard's login page. Without this the
     HTML loads but every .js/.wasm request returns a login page with a 200,
     which fails in the browser as a MIME-type error rather than a visible 401.
  3. **A CSP relaxation** for WebAssembly. The dashboard's policy has no
     ``wasm-unsafe-eval``, which makes ``WebAssembly.instantiate`` throw. The
     OpenCascade kernel is WebAssembly, so the viewer cannot run behind the
     dashboard's default policy. This module replaces the CSP for /stepstudio/
     responses only; every other route keeps the stricter one.

Nothing here touches the dashboard's own routes, auth, or data. Removing the
import and restarting restores the previous behaviour exactly.
"""

from __future__ import annotations

import gzip
import logging
from html import escape
from pathlib import Path

from fastapi import FastAPI, Request
from fastapi.responses import FileResponse

logger = logging.getLogger("stepstudio")

#: URL prefix the app is published under. Must match the ``base`` the front-end
#: was built with (see vite.config.js) and the nginx location that routes here.
PREFIX = "/stepstudio"

#: Where the built app lives. The dashboard runs as this user, so this is an
#: absolute path rather than anything relative to the app directory.
APP_DIR = Path("/home/b2a/workspace/dist")

#: The sheep demo — a three.js scene, published at the short /sheep URL.
#:
#: It lives inside the same build (workspace/dist/sheep, generated by
#: scripts/vendor-sheep.mjs) but is served at a second prefix. It is NOT part of
#: the STEP Studio app and shares none of its code.
SHEEP_DIR = Path("/home/b2a/workspace/dist/sheep")
SHEEP_PREFIX = "/sheep"

#: Types the browser refuses to run correctly if served as anything else.
#: ``.wasm`` in particular must be application/wasm or instantiateStreaming
#: rejects it — and a wrong type here is a silent, confusing failure.
MIME_BY_SUFFIX = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json",
    ".wasm": "application/wasm",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".txt": "text/plain; charset=utf-8",
    ".map": "application/json",
    # Fonts. Absent from this table originally, so .woff2 fell through to
    # application/octet-stream — which, with ``X-Content-Type-Options: nosniff``
    # set by the dashboard, is a configuration browsers may legitimately refuse
    # to load. It worked by leniency; this makes it correct.
    ".woff2": "font/woff2",
    ".woff": "font/woff",
}

#: The dashboard's CSP, plus what WebAssembly needs, for /stepstudio/ only.
#:
#:   - ``wasm-unsafe-eval``   permits WebAssembly.instantiate/compile
#:   - ``unsafe-eval``        REQUIRED, and worth understanding before removing:
#:                            OpenCascade is exposed through emscripten's embind,
#:                            whose runtime builds argument-marshalling invokers
#:                            with ``new Function(...)``. Without 'unsafe-eval'
#:                            the kernel throws a CSP violation the first time a
#:                            bound method is called, so STEP parsing fails.
#:                            There is no narrower directive for this: eval is not
#:                            source-based, so a hash or nonce cannot cover it.
#:   - ``blob:`` in worker-src lets the bundler start its worker from a blob URL.
#:
#: Scope of the relaxation: this header is applied only to /stepstudio/ responses.
#: The dashboard's own pages keep the stricter policy untouched. The relaxed page
#: serves only static assets built from this repository and renders no
#: user-supplied markup, so the practical exposure is limited to a script
#: injection into that page — which ``script-src 'self'`` already constrains.
STEPSTUDIO_CSP = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' blob:; "
    "worker-src 'self' blob:; "
    "style-src 'self' 'unsafe-inline'; "
    "img-src 'self' data: blob:; "
    "connect-src 'self'; "
    "font-src 'self' data:; "
    "frame-ancestors 'self'"
)


#: Suffixes whose contents are safe to cache forever. These are the Vite-emitted
#: names, which carry a content hash — a changed file gets a changed URL, so a
#: stale copy can never be served. index.html is NOT here: it is the one
#: unhashed name, and caching it would hide a deploy.
_CACHEABLE_SUFFIXES = {
    ".js",
    ".mjs",
    ".css",
    ".wasm",
    ".png",
    ".svg",
    ".ico",
    ".woff2",
}

#: Suffixes worth compressing, cheapest-to-most-expensive to be worth the CPU.
#:
#: This exists because nginx does NOT compress them. Its `gzip_types` is left at
#: the default (``text/html``) — every other type is commented out in
#: nginx.conf — so HTML arrives gzipped and everything else arrives raw. For this
#: app that means the 7.25 MB OpenCascade wasm is downloaded in full on every
#: cold visit. Measured savings: wasm 7.25 -> 2.94 MB (59%), the JS bundle
#: 0.77 -> 0.19 MB (75%).
#:
#: Compressing here rather than asking nginx to is a deliberate response to a
#: constraint: nginx.conf is root-owned and there is no sudo on this box, so
#: `gzip_types application/wasm ...` cannot be added. nginx only gzips the types
#: in its own list, so a Content-Encoding set upstream is passed through
#: untouched for everything else — which is what makes this work at all.
#:
#: woff2 is absent on purpose: it is already Brotli-compressed internally, so
#: gzipping it costs CPU to make it very slightly larger.
_COMPRESSIBLE_SUFFIXES = {
    ".js",
    ".mjs",
    ".css",
    ".json",
    ".wasm",
    ".svg",
    ".map",
}

#: Below this size, the gzip header and the CPU cost are not worth it — and the
#: dashboard's own HTML responses are already compressed by nginx.
_GZIP_MIN_BYTES = 1024

#: The dashboard's own no-store value, reused so the two agree exactly.
NO_STORE = "no-store, no-cache, must-revalidate, max-age=0"


def _gzip_bytes(raw: bytes, level: int = 6) -> bytes:
    """Gzip a payload, returning the original if compression is not a win.

    Small or already-compressed inputs can come out larger; the caller only sends
    Content-Encoding when the returned bytes are actually smaller, so this never
    makes a response worse.
    """
    compressed = gzip.compress(raw, level)
    return compressed if len(compressed) < len(raw) else raw


def _safe_target(root: Path, rel: str) -> Path | None:
    """Resolve ``rel`` under ``root``, or None if it escapes the directory.

    Guards against ``..`` traversal and absolute paths in the request. The prefix
    is stripped by the caller; anything still resolving outside the build
    directory is rejected rather than served.
    """
    candidate = (root / rel.lstrip("/")).resolve()
    try:
        candidate.relative_to(root.resolve())
    except ValueError:
        return None
    return candidate


async def serve_stepstudio_files(request, rel: str = ""):
    """Return the file for a /stepstudio/ request, or a 404 page.

    The CAD viewer is a single-page app, so an unknown extensionless path falls
    back to its index rather than 404ing.
    """
    return await serve_file(request, APP_DIR, rel, spa_fallback=True)


async def serve_file(request, directory: Path, rel: str, *, spa_fallback: bool, cache_seconds: int | None = None):
    """Serve one file from ``directory``, gzipped when the client accepts it.

    Shared by both mounted prefixes so the traversal guard, MIME table,
    conditional gzip and cache rules cannot drift apart between them.
    ``spa_fallback`` decides what an unknown extensionless path does: the CAD
    viewer is a single-page app and falls back to its index, the sheep page is
    not and returns a real 404.

    ``cache_seconds`` is the max-age for hashed assets under this prefix; None
    means "never cache". index.html is always no-store regardless, since it is
    the one unhashed name and caching it would hide a deploy.
    """
    if not directory.is_dir():
        return _not_built()

    rel = (rel or "").strip("/")
    if not rel:
        rel = "index.html"

    target = _safe_target(directory, rel)
    if target is None:
        logger.warning("rejected traversal attempt for %r under %s", rel, directory)
        return _not_found(rel)

    if target.is_dir():
        target = target / "index.html"

    if not target.is_file():
        # A missing typed asset (.js, .wasm) must 404 rather than quietly return
        # HTML: the browser would reject it as a MIME error, which is far more
        # confusing than a clean 404. Only extensionless paths may fall back.
        has_extension = "." in Path(rel).name
        fallback = directory / "index.html"
        if has_extension or not spa_fallback or not fallback.is_file():
            return _not_found(rel)
        target = fallback

    body = target.read_bytes()
    headers = {}

    if target.name == "index.html":
        headers["Cache-Control"] = NO_STORE
    elif cache_seconds:
        headers["Cache-Control"] = f"public, max-age={cache_seconds}"

    suffix = target.suffix.lower()
    # nginx leaves these types uncompressed (see _COMPRESSIBLE_SUFFIXES), so the
    # work is done here. Vary is set whenever the response *could* differ by
    # encoding, including when we chose not to compress this particular body, or
    # a shared cache could hand a gzip payload to a client that cannot read it.
    if suffix in _COMPRESSIBLE_SUFFIXES:
        headers["Vary"] = "Accept-Encoding"
        accepted = (request.headers.get("accept-encoding") or "").lower()
        if len(body) >= _GZIP_MIN_BYTES and "gzip" in accepted:
            compressed = _gzip_bytes(body)
            if len(compressed) < len(body):
                body = compressed
                headers["Content-Encoding"] = "gzip"

    from fastapi import Response

    return Response(
        content=body,
        media_type=MIME_BY_SUFFIX.get(suffix, "application/octet-stream"),
        headers=headers,
    )


def _not_found(rel: str):
    from fastapi.responses import HTMLResponse

    return HTMLResponse(
        f"<h1>Not found</h1><p>No such file in the STEP Studio build: "
        f"<code>{escape(rel)}</code></p>",
        status_code=404,
    )


async def serve_sheep_files(request, rel: str = ""):
    """Return the file for a /sheep/ request, or a 404.

    Deliberately no SPA fallback, unlike the CAD viewer: a missing asset here is a
    real 404, not a route the client-side router should resolve. Gzip, the MIME
    table and the traversal guard are shared with the viewer so the two cannot
    drift apart.

    Assets get a 1-day max-age rather than the viewer's immutable year: the font
    files are content-hashed by scripts/vendor-sheep.mjs, but three.min.js is not,
    so a long-lived cache entry could pin a stale library.
    """
    return await serve_file(
        request, SHEEP_DIR, rel, spa_fallback=False, cache_seconds=86400
    )


def _not_built():
    from fastapi.responses import HTMLResponse

    return HTMLResponse(
        "<h1>STEP Studio is not built</h1>"
        f"<p>Expected a build at <code>{APP_DIR}</code>. Run "
        "<code>npm run build</code> in /home/b2a/workspace.</p>",
        status_code=503,
    )


def install(app: FastAPI) -> None:
    """Mount the viewer. Idempotent, so a reload does not double-register."""
    if getattr(app.state, "_stepstudio_installed", False):
        return
    app.state._stepstudio_installed = True

    # Routes are registered against the app object directly, so they must exist
    # before Starlette builds its route table. Routing is by path, not
    # registration order, and none of the dashboard's patterns overlap
    # /stepstudio/... except the /{username}/{project} catch-all — which is
    # shadowed for us because a literal path segment outranks a parameter.
    @app.get(PREFIX, include_in_schema=False)
    async def stepstudio_root(request: Request):
        return await serve_stepstudio_files(request, "")

    @app.get(PREFIX + "/{rel:path}", include_in_schema=False)
    async def stepstudio_asset(request: Request, rel: str):
        return await serve_stepstudio_files(request, rel)

    # The sheep demo at the short /sheep URL. Registered here because this module
    # is already imported before the dashboard's route table is built, and it is
    # already reached by the same "install early, CSP later" contract. Note the
    # path is /sheep and NOT /stepstudio/sheep — the page under the build
    # directory is reached at whichever prefix routes to it.
    @app.get(SHEEP_PREFIX, include_in_schema=False)
    async def sheep_root(request: Request):
        return await serve_sheep_files(request, "")

    @app.get(SHEEP_PREFIX + "/{rel:path}", include_in_schema=False)
    async def sheep_asset(request: Request, rel: str):
        return await serve_sheep_files(request, rel)

    logger.info(
        "STEP Studio mounted at %s (serving %s); sheep at %s (serving %s)",
        PREFIX, APP_DIR, SHEEP_PREFIX, SHEEP_DIR,
    )


def install_csp(app: FastAPI) -> None:
    """Register the CSP-relaxing middleware.

    MUST be called after every other middleware has been registered. Starlette
    composes middleware in reverse registration order — the LAST registered is
    the OUTERMOST — so this has to come after the dashboard's
    security_headers_middleware to run on the way out and replace the CSP it set.
    Registering it earlier silently has no effect, which is a confusing failure
    because everything else about the deployment looks correct.
    """
    if getattr(app.state, "_stepstudio_csp_installed", False):
        return
    app.state._stepstudio_csp_installed = True

    @app.middleware("http")
    async def stepstudio_csp_middleware(request, call_next):
        response = await call_next(request)
        path = request.url.path
        rp = request.scope.get("root_path", "")
        rel = path[len(rp):] if (rp and path.startswith(rp)) else path
        if rel == PREFIX or rel.startswith(PREFIX + "/"):
            response.headers["Content-Security-Policy"] = STEPSTUDIO_CSP
            # The wasm is fetched by the worker from the same origin; be explicit
            # so a future proxy change cannot break it.
            response.headers["Cross-Origin-Resource-Policy"] = "same-origin"
            # Cache-Control: the dashboard's security_headers_middleware stamps
            # no-store on every response, and this middleware is outermost, so
            # this is the only place the value survives *within the app*.
            #
            # It does NOT survive to the browser. The nginx site config has its
            # own `add_header Cache-Control "no-store" always`, so the edge emits
            # no-store whatever is set here, and every visit re-fetches the
            # bundle. Changing that needs root (nginx.conf is not writable from
            # this account) — which is why the gzip below matters more than this
            # header does.
            #
            # Vite fingerprints the asset filenames, so a changed file is a
            # changed URL: immutable is safe for them. index.html is the one
            # unhashed name and must never be cached, or a deploy would not be
            # picked up until users hard-refreshed.
            suffix = Path(rel).suffix.lower()
            if response.status_code == 200 and suffix in _CACHEABLE_SUFFIXES:
                response.headers["Cache-Control"] = "public, max-age=31536000, immutable"
            else:
                # Anything else — index.html, the SPA fallback for an extensionless
                # deep link, and any 404 — must not be cached. A missing asset is
                # excluded on the status check above: pinning a 404 for a year
                # would outlive the deploy that fixes it.
                response.headers["Cache-Control"] = NO_STORE
        return response

    logger.info("STEP Studio CSP override registered for %s", PREFIX)
