[program:tmux-dashboard]
command=python3 /home/nimrod_rotem/tmux-dashboard/app.py
directory=/home/nimrod_rotem/tmux-dashboard
user=nimrod_rotem
autostart=true
autorestart=true
stderr_logfile=/var/log/tmux-dashboard.err.log
stdout_logfile=/var/log/tmux-dashboard.out.log
environment=HOME="/home/nimrod_rotem"
